# Generated by Django 5.0.6 on 2024-08-02 03:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000000),
            preserve_default=False,
        ),
    ]
